### ISSUE TITLE
[Task] refactor main to smoothly handle gui or cli mode

### ISSUE THREAD

**Issue by coreybasden** [hbarton2/cscd350-f24-UnhandledExceptions#100]
perhaps create a cli class and a gui class then refactor main into simply asking which mode the user wants, and then looping either cli.run() or gui.run() depending.

**Comment by RyanHirte** [comment]
should take long time I think, 3 - 4 hours.

**Comment by zDmarkley** [comment]
we could hold different main(s) for both CLI and GUI choices. main could just be managing if the user chooses 'cli' or 'gui'

**Comment by coreybasden** [comment]
done
