### ISSUE TITLE
redo\undo stacks

### ISSUE THREAD

**Issue by coreybasden** [hbarton2/cscd350-f24-UnhandledExceptions#140]
Initial guess, have 2 project wide lists (undo and redo). every command gets added to the undo list. every time we undo, add it to the redo list?

**Comment by coreybasden** [comment]
thought: our CLI switch statement takes a string (from the user) to know what command to execute with which values. for our undo stack, we could literally make that CLI switch statement public and send strings to it to execute commands.

**Comment by RyanHirte** [comment]
time estimate: 4 hours
