### ISSUE TITLE
6 design patterns

### ISSUE THREAD

**Issue by RyanHirte** [hbarton2/cscd350-f24-UnhandledExceptions#142]
We need at least 6 design patterns implemented in our project.

Time estimate: 2 weeks (whole sprint)

**Comment by RyanHirte** [comment]
MVC is a design pattern.

**Comment by RyanHirte** [comment]
Momento for undo and redo

**Comment by RyanHirte** [comment]
Patterns don't need to be unique.

**Comment by RyanHirte** [comment]
Factory for creating objects.

Example: Relationship line but for different relationships

**Comment by RyanHirte** [comment]
Singleton for GUI and CLI

**Comment by zDmarkley** [comment]
Could use either Adapter or Bridge to be able to save/load data from either CLI or GUI

**Comment by RyanHirte** [comment]
Singleton cannot be applied to our GUI because of the way javaFX constructs it.

**Comment by RyanHirte** [comment]
Singleton for Data.java?

**Comment by Lantzer** [comment]
Builder for creating ClassBox's

**Comment by zDmarkley** [comment]
Observer for keeping track of when changes to the model have been made
